# Generated by Django 5.2.8 on 2026-03-27 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_receipt_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='demo_expires_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
    ]
