# Generated by Django 5.2.8 on 2026-03-28 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_organization_demo_expires_at_organization_is_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_template',
            field=models.BooleanField(default=False, help_text='Template organizations are used as source for demo data'),
        ),
    ]
