# Generated by Django 5.2.8 on 2026-03-28 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_tenant_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='relationship',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
