# Generated by Django 5.2.8 on 2026-04-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_report_relationship_alter_report_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='occurred_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
