# Generated by Django 5.2.8 on 2026-04-04 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_report_occurred_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantpayment',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.organization'),
        ),
        migrations.AlterField(
            model_name='tenantpayment',
            name='custom_id',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
        migrations.AddConstraint(
            model_name='tenantpayment',
            constraint=models.UniqueConstraint(fields=('organization', 'custom_id'), name='unique_payment_code_per_org'),
        ),
    ]
