# Generated by Django 5.2.8 on 2026-04-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_tenantpayment_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
